### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by Radiotechniman** [kerkenit/nl.marcovantklooster.sshclient#1]
app not working on the 0.10.5 beta, atleast i cannot add any servers

**Comment by markaswift** [comment]
Is this no longer being maintained?

**Comment by kerkenit** [comment]
This app is maintained, only there is a lack of time. Feel free to send a pull request.

**Comment by kerkenit** [comment]
Fixed in 41c6d5588a4e3d35651e243051637addae790767

**Comment by Radiotechniman** [comment]
Awesome,  thanks!
