### ISSUE TITLE
v3 compatibility?

### ISSUE THREAD

**Issue by JohanBendz** [kerkenit/nl.marcovantklooster.sshclient#6]
Hi Marco.
It would be much aprechiated if you took the time and effort to update the app with v3 compatibility and published a new version to the app store.

Thanks in advance!

// Johan

**Comment by gine78** [comment]
+1 is it possible that u update this one?

**Comment by HenkVanA** [comment]
I used the app.json version from Pull Request https://github.com/kerkenit/nl.marcovantklooster.sshclient/pull/5/commits/7c5999e982dd3be327591640f73cf17e18cd3016, which solved the issue for me. My current Homey version is 3.2.0

**Comment by gine78** [comment]
> I used the app.json version from Pull Request [7c5999e](https://github.com/kerkenit/nl.marcovantklooster.sshclient/commit/7c5999e982dd3be327591640f73cf17e18cd3016), which solved the issue for me. My current Homey version is 3.2.0

How dit you install it on Homey?

**Comment by HenkVanA** [comment]
Via a CLI install, see https://www.youtube.com/watch?v=JnjAyWKSEIE

**Comment by bochove** [comment]
You can now also test from:
https://homey.app/en-us/app/nl.marcovantklooster.sshclient/SSH-Client/test/
