### ISSUE TITLE
unable to use on homey 4.2.0

### ISSUE THREAD

**Issue by xfil3r** [kerkenit/nl.marcovantklooster.sshclient#7]
Hello,

the app cannot be installed via app store (it gives incompatible version). following a previous thread, I managed to install it manually via node.js cli and it is now showing in my homey but I'm not able to use it: the device itself does not have any control and it does not show up in flow setup.

**Comment by bochove** [comment]
You can now also test from:
https://homey.app/en-us/app/nl.marcovantklooster.sshclient/SSH-Client/test/

**Comment by xfil3r** [comment]
Hello,

I'm now on homey 5.0.0rc26. The app can be installed correctly from your last link and seems usable in both devices and flows.
BTW, I'm not able to modify the action in the flow: see screenshot below for card modification
![Screenshot_20200827-133319.jpg](https://user-images.githubusercontent.com/65403353/91437290-f3570d00-e869-11ea-9c7d-6c6c849163ab.jpg)
Where nothing can be tapped or modified.

Emanuele

**Comment by bochove** [comment]
Hi,

That is normal for trigger cards, the tokens shown on that page can be used in the rest of the flow though.

So what you have there is the 'when' card.
The tokens can be used with other cards in the 'and' and 'then' sections of a flow.
In the 'and' section you could add a logic card 'equals' to specify that 'Device name' must equal 'xxxx' and in the 'then' section you could add a mobile-->notification card and set a notification message as:
'Device name' sent error 'Complete error message', so you will be notified of what went wrong.
